


		--AGENCY

		--NO FILTER

		SET ANSI_NULLS ON SET ANSI_PADDING ON SET QUOTED_IDENTIFIER ON 
        SET ANSI_WARNINGS ON SET CONCAT_NULL_YIELDS_NULL ON 
        SET ARITHABORT ON SET ANSI_NULL_DFLT_ON ON 
        EXEC USP_GetDocumentDetails '8125','','','','','','','0','100'    -- 2 sec


		--WITH FILTERS

		SET ANSI_NULLS ON SET ANSI_PADDING ON SET QUOTED_IDENTIFIER ON 
        SET ANSI_WARNINGS ON SET CONCAT_NULL_YIELDS_NULL ON 
        SET ARITHABORT ON SET ANSI_NULL_DFLT_ON ON 
        EXEC USP_GetDocumentDetails '8125','a','','','','','','0','100'   -- 1 sec


		SET ANSI_NULLS ON SET ANSI_PADDING ON SET QUOTED_IDENTIFIER ON 
        SET ANSI_WARNINGS ON SET CONCAT_NULL_YIELDS_NULL ON 
        SET ARITHABORT ON SET ANSI_NULL_DFLT_ON ON 
        EXEC USP_GetDocumentDetails '8125','a','a','','','','','0','100' -- 1 sec


		SET ANSI_NULLS ON SET ANSI_PADDING ON SET QUOTED_IDENTIFIER ON 
        SET ANSI_WARNINGS ON SET CONCAT_NULL_YIELDS_NULL ON 
        SET ARITHABORT ON SET ANSI_NULL_DFLT_ON ON 
        EXEC USP_GetDocumentDetails '8125','a','a','a','','','','0','100' -- 1 sec

		
		SET ANSI_NULLS ON SET ANSI_PADDING ON SET QUOTED_IDENTIFIER ON 
        SET ANSI_WARNINGS ON SET CONCAT_NULL_YIELDS_NULL ON 
        SET ARITHABORT ON SET ANSI_NULL_DFLT_ON ON 
        EXEC USP_GetDocumentDetails '8125','a','a','a','File Upload-Test file upload','','','0','100' -- 3 sec


		SET ANSI_NULLS ON SET ANSI_PADDING ON SET QUOTED_IDENTIFIER ON 
        SET ANSI_WARNINGS ON SET CONCAT_NULL_YIELDS_NULL ON 
        SET ARITHABORT ON SET ANSI_NULL_DFLT_ON ON 
        EXEC USP_GetDocumentDetails '8125','a','a','a','File Upload-Test file upload','agency','','0','100' -- 3 sec


		--CASEWORKER

		--NO FILTER

		SET ANSI_NULLS ON SET ANSI_PADDING ON SET QUOTED_IDENTIFIER ON 
        SET ANSI_WARNINGS ON SET CONCAT_NULL_YIELDS_NULL ON 
        SET ARITHABORT ON SET ANSI_NULL_DFLT_ON ON 
        EXEC USP_GetDocumentDetails '8125','','','','','','','0','100'    -- 1 sec

		--WITH FILTERS

		SET ANSI_NULLS ON SET ANSI_PADDING ON SET QUOTED_IDENTIFIER ON 
        SET ANSI_WARNINGS ON SET CONCAT_NULL_YIELDS_NULL ON 
        SET ARITHABORT ON SET ANSI_NULL_DFLT_ON ON 
        EXEC USP_GetDocumentDetails '17129','a','','','','','','0','100'  -- 25 sec


		SET ANSI_NULLS ON SET ANSI_PADDING ON SET QUOTED_IDENTIFIER ON 
        SET ANSI_WARNINGS ON SET CONCAT_NULL_YIELDS_NULL ON 
        SET ARITHABORT ON SET ANSI_NULL_DFLT_ON ON 
        EXEC USP_GetDocumentDetails '17129','a','a','','','','','0','100'  -- 22 sec


		SET ANSI_NULLS ON SET ANSI_PADDING ON SET QUOTED_IDENTIFIER ON 
        SET ANSI_WARNINGS ON SET CONCAT_NULL_YIELDS_NULL ON 
        SET ARITHABORT ON SET ANSI_NULL_DFLT_ON ON 
        EXEC USP_GetDocumentDetails '17129','a','a','a','','','','0','100' -- 23 sec


		SET ANSI_NULLS ON SET ANSI_PADDING ON SET QUOTED_IDENTIFIER ON 
        SET ANSI_WARNINGS ON SET CONCAT_NULL_YIELDS_NULL ON 
        SET ARITHABORT ON SET ANSI_NULL_DFLT_ON ON 
        EXEC USP_GetDocumentDetails '17129','a','a','a','File Upload-Test file upload','','','0','100' -- 4 sec


		SET ANSI_NULLS ON SET ANSI_PADDING ON SET QUOTED_IDENTIFIER ON 
        SET ANSI_WARNINGS ON SET CONCAT_NULL_YIELDS_NULL ON 
        SET ARITHABORT ON SET ANSI_NULL_DFLT_ON ON 
        EXEC USP_GetDocumentDetails '17129','a','a','a','File Upload-Test file upload','agency','','0','100' -- 3 sec



		--ADOPTIVE PARENT

		--NO FILTER

		SET ANSI_NULLS ON SET ANSI_PADDING ON SET QUOTED_IDENTIFIER ON 
        SET ANSI_WARNINGS ON SET CONCAT_NULL_YIELDS_NULL ON 
        SET ARITHABORT ON SET ANSI_NULL_DFLT_ON ON 
        EXEC USP_GetDocumentDetails '8125','','','','','','','0','100'    -- 1 sec


		--WITH FILTERS

		SET ANSI_NULLS ON SET ANSI_PADDING ON SET QUOTED_IDENTIFIER ON 
        SET ANSI_WARNINGS ON SET CONCAT_NULL_YIELDS_NULL ON 
        SET ARITHABORT ON SET ANSI_NULL_DFLT_ON ON 
        EXEC USP_GetDocumentDetails '18183','a','','','','','345523','0','100'  -- 0 sec


		SET ANSI_NULLS ON SET ANSI_PADDING ON SET QUOTED_IDENTIFIER ON 
        SET ANSI_WARNINGS ON SET CONCAT_NULL_YIELDS_NULL ON 
        SET ARITHABORT ON SET ANSI_NULL_DFLT_ON ON 
        EXEC USP_GetDocumentDetails '18183','a','a','','','','345523','0','100'  -- 0 sec





	