

use mapmachformAADV;
ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;        use mapmachformAAI
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformAAU
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformABI
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformACC
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformADCT
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformADOPTABSC
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformADOPTIONCHOICESOFTEXAS
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformAGAPE
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformAGC
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformAOI
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformATFS
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformAUA
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformBH
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformBRIGHT
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformBUCKNER
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformBase
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformCCD
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformCCDIOBR
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformCCK
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformCCN
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformCDMAP01
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformCDMAP03
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformCFS
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformCH
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformCOTW
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformCPMAPROLES01
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformCPMQ01
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformCSS
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformCSSMT
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformCTMAPUAT01
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformCTMAPUAT02
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformDEMO
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformDEVROLES
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformDILLONADOPT
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformDILLONTEST
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformDRC
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformEBG
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformECKERD
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformFAC
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformFBA
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformFCAD
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformFOSTER
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformFOSTERCARE
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformFULLCIRCLEADOPTIONS
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformGOL
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformHATW
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformHAVENADOPTIONS
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformHHA
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformHOA
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformHOAA
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformHOPE
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformIFI
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformLH
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformLHTEST
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformLMI
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformLSSMN
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformLSSMT
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformMAPSW
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformOWAS
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformOrginal
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformPREMIER
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformQAROLES
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformSCL
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformSDC
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformSTAGEROLES
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformTDH
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;   use mapmachformTRH
  ;  ALTER TABLE `ap_forms` ADD `sent_inquiry_form_notifications` ENUM('yes','no') NOT NULL DEFAULT 'yes' AFTER `form_auto_approvals`;