

use mapmachformAADV;
ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';        use mapmachformAAI
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformAAU
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformABI
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformACC
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformADCT
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformADOPTABSC
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformADOPTIONCHOICESOFTEXAS
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformAGAPE
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformAGC
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformAOI
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformATFS
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformAUA
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformBH
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformBRIGHT
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformBUCKNER
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformBase
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformCCD
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformCCDIOBR
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformCCK
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformCCN
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformCDMAP01
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformCDMAP03
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformCFS
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformCH
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformCOTW
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformCPMAPROLES01
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformCPMQ01
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformCSS
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformCSSMT
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformCTMAPUAT01
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformCTMAPUAT02
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformDEMO
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformDEVROLES
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformDILLONADOPT
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformDILLONTEST
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformDRC
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformEBG
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformECKERD
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformFAC
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformFBA
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformFCAD
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformFOSTER
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformFOSTERCARE
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformFULLCIRCLEADOPTIONS
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformGOL
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformHATW
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformHAVENADOPTIONS
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformHHA
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformHOA
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformHOAA
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformHOPE
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformIFI
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformLH
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformLHTEST
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformLMI
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformLSSMN
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformLSSMT
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformMAPSW
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformOWAS
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformOrginal
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformPREMIER
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformQAROLES
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformSCL
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformSDC
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformSTAGEROLES
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformTDH
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';   use mapmachformTRH
  ;  ALTER TABLE `ap_forms` CHANGE `sent_inquiry_form_notifications` `form_email_notify` ENUM('yes','no') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'yes';