DISABLE TRIGGER [UpdateRelContactIds] ON [dbo].[Rel_Relationship]
GO

SELECT distinct RELATIONSHIPID,RELATIONSHIPTYPEID,CONNECTIONID
INTO #APBMTEMP
FROM REL_RELATIONSHIP 
WHERE  CONNECTIONID IN (SELECT CONNECTIONID FROM rel_relationship WHERE relationshiptypeid = -101 AND BMID IS NULL)
AND RELATIONSHIPTYPEID = -102

CREATE TABLE #MULTICOUNTTEMP
(ID INT IDENTITY(1,1),
CONNECTIONID INT,
COUNTCON INT)

INSERT INTO #MULTICOUNTTEMP
SELECT  CONNECTIONID, Count(CONNECTIONID) AS COUNTCON
FROM #APBMTEMP
GROUP BY CONNECTIONID
HAVING  Count(CONNECTIONID) > 1

SELECT  CONNECTIONID, Count(CONNECTIONID) AS COUNTCON
INTO #COUNTTEMP
FROM #APBMTEMP
GROUP BY CONNECTIONID
HAVING  Count(CONNECTIONID) = 1

UPDATE  R
SET R.BMID = A.RELATIONSHIPID 
,R.BPflag = 1
FROM REL_RELATIONSHIP R
JOIN #APBMTEMP A
ON R.CONNECTIONID = A.CONNECTIONID
WHERE A.CONNECTIONID IN (
SELECT  CONNECTIONID  FROM #COUNTTEMP)
AND r.relationshiptypeid = -101
and r.BMID is null

DECLARE @MINCOUNT INT 
,@MAXCOUNT INT
,@CONNECTIONID INT
,@RELATIONSHIPID VARCHAR(100)

SELECT @MAXCOUNT = COUNT(ID) FROM #MULTICOUNTTEMP  
SET @MINCOUNT = 1
WHILE(@MINCOUNT<=@MAXCOUNT)
BEGIN
	SELECT @CONNECTIONID = CONNECTIONID FROM #MULTICOUNTTEMP WHERE ID = @MINCOUNT

	SELECT @RELATIONSHIPID =   STUFF((SELECT ',' + CONVERT(VARCHAR(10),(RELATIONSHIPID) )
							FROM #APBMTEMP
							WHERE CONNECTIONID = @CONNECTIONID
					FOR XML PATH(''), TYPE
					).value('.', 'NVARCHAR(MAX)') 
				,1,1,'')
				
	UPDATE  REL_RELATIONSHIP
	SET BMID = @RELATIONSHIPID
	,R.BPflag = 1
	WHERE ConnectionId =  @CONNECTIONID
	AND RelationshipTypeId = -101
 
	SET @MINCOUNT = @MINCOUNT+1
END

GO

ENABLE TRIGGER [UpdateRelContactIds] ON [dbo].[Rel_Relationship]
GO