
use mapform

exec usp_UpdateLibraryData '<lib_data>
		<AP1Fname>
			<name>AP1Fname</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>test sunday2</value>
		</AP1Fname>
		<AP1MName>
			<name>AP1MName</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>my2</value>
		</AP1MName>
		<AP1Lname>
			<name>AP1Lname</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>test lname</value>
		</AP1Lname>
		<AP1ActAge>
			<name>AP1ActAge</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>undefined</value>
		</AP1ActAge>
		<AP1Age>
			<name>AP1Age</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>undefined</value>
		</AP1Age>
		<AP1BirthCity>
			<name>AP1BirthCity</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>test city</value>
		</AP1BirthCity>
		<AP1BirthCountry>
			<name>AP1BirthCountry</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>1</value>
		</AP1BirthCountry>
		<AP1BirthName>
			<name>AP1BirthName</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>test bname</value>
		</AP1BirthName>
		<AP1BirthState>
			<name>AP1BirthState</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>MS</value>
		</AP1BirthState>
		<AP1CellPhone>
			<name>AP1CellPhone</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>944-795-9086</value>
		</AP1CellPhone>
		<AP1Degree>
			<name>AP1Degree</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>B.A.</value>
		</AP1Degree>
		<AP1DegreeYear>
			<name>AP1DegreeYear</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>2014</value>
		</AP1DegreeYear>
		<AP1DOB>
			<name>AP1DOB</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>2016-01-01</value>
		</AP1DOB>
		<AP1Email>
			<name>AP1Email</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>test@msi.in</value>
		</AP1Email>
		<AP1Ethnicity>
			<name>AP1Ethnicity</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>Bi-Racial</value>
		</AP1Ethnicity>
		<AP1Gender>
			<name>AP1Gender</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>M</value>
		</AP1Gender>
		<AP1Nickname>
			<name>AP1Nickname</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>test nickname</value>
		</AP1Nickname>
		<AP1Race>
			<name>AP1Race</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>White  Caucasian</value>
		</AP1Race>
		<AP1SSN>
			<name>AP1SSN</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>123456987</value>
		</AP1SSN>
		<AP1County>
			<name>AP1County</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>test county</value>
		</AP1County>
		<AP1WorkPhone>
			<name>AP1WorkPhone</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>844-795-9086</value>
		</AP1WorkPhone>
		<AP2Fname>
			<name>AP2Fname</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>ap2 test fname</value>
		</AP2Fname>
		<AP2Lname>
			<name>AP2Lname</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>ap2 test lname</value>
		</AP2Lname>
		<AP2MName>
			<name>AP2MName</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>undefined</value>
		</AP2MName>
		<AP2ActAge>
			<name>AP2ActAge</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>undefined</value>
		</AP2ActAge>
		<AP2Age>
			<name>AP2Age</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>undefined</value>
		</AP2Age>
		<AP2Add1>
			<name>AP2Add1</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>undefined</value>
		</AP2Add1>
		<AP2Add2>
			<name>AP2Add2</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>undefined</value>
		</AP2Add2>
		<AP2BirthCity>
			<name>AP2BirthCity</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>undefined</value>
		</AP2BirthCity>
		<AP2BirthCountry>
			<name>AP2BirthCountry</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>undefined</value>
		</AP2BirthCountry>
		<AP2BirthName>
			<name>AP2BirthName</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>undefined</value>
		</AP2BirthName>
		<AP2BirthState>
			<name>AP2BirthState</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>undefined</value>
		</AP2BirthState>
		<AP2CellPhone>
			<name>AP2CellPhone</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>undefined</value>
		</AP2CellPhone>
		<AP2City>
			<name>AP2City</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>undefined</value>
		</AP2City>
		<AP2County>
			<name>AP2County</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>undefined</value>
		</AP2County>
		<AP2Country>
			<name>AP2Country</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>undefined</value>
		</AP2Country>
		<AP2Degree>
			<name>AP2Degree</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>undefined</value>
		</AP2Degree>
		<AP2DOB>
			<name>AP2DOB</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>2016-01-01</value>
		</AP2DOB>
		<AP2Email>
			<name>AP2Email</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>test2@msi.in</value>
		</AP2Email>
		<AP2Ethnicity>
			<name>AP2Ethnicity</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>undefined</value>
		</AP2Ethnicity>
		<AP2Gender>
			<name>AP2Gender</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>undefined</value>
		</AP2Gender>
		<AP2Nickname>
			<name>AP2Nickname</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>undefined</value>
		</AP2Nickname>
		<AP2WorkPhone>
			<name>AP2WorkPhone</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>undefined</value>
		</AP2WorkPhone>
		<HomePhone>
			<name>HomePhone</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>undefined</value>
		</HomePhone>
		<City>
			<name>City</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>undefined</value>
		</City>
		<State>
			<name>State</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>undefined</value>
		</State>
		<Zip>
			<name>Zip</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>undefined</value>
		</Zip>
		<Add2>
			<name>Add2</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>undefined</value>
		</Add2>
		<Add1>
			<name>Add1</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>undefined</value>
		</Add1>
		<ap1signature>
			<name>ap1signature</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>undefined</value>
		</ap1signature>
		<ap2signature>
			<name>ap2signature</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>undefined</value>
		</ap2signature>
		<Med_1Sex>
			<name>Med_1Sex</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>0</is_system>
			<value>undefined</value>
		</Med_1Sex>
		<Med_2Sex>
			<name>Med_2Sex</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>0</is_system>
			<value>undefined</value>
		</Med_2Sex>
		<AP2SSN>
			<name>AP2SSN</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>undefined</value>
		</AP2SSN>
		<Country>
			<name>Country</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>undefined</value>
		</Country>
		<County>
			<name>County</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
			<value>undefined</value>
		</County>
		<radio_1452071124454>
			<name>radio_1452071124454</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>0</is_system>
			<value>undefined</value>
		</radio_1452071124454>
		<radio_1452071125682>
			<name>radio_1452071125682</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>0</is_system>
			<value>undefined</value>
		</radio_1452071125682>
		<radio_1452071126181>
			<name>radio_1452071126181</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>0</is_system>
			<value>undefined</value>
		</radio_1452071126181>
		<select_1452071437616>
			<name>select_1452071437616</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>0</is_system>
			<value>undefined</value>
		</select_1452071437616>
		<select_1452071457722>
			<name>select_1452071457722</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>0</is_system>
			<value>undefined</value>
		</select_1452071457722>
		<select_1452071490963>
			<name>select_1452071490963</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>0</is_system>
			<value>undefined</value>
		</select_1452071490963>
		<checkbox_1452071506093>
			<name>checkbox_1452071506093</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>0</is_system>
			<value>undefined</value>
		</checkbox_1452071506093>
		<checkbox_1452071521461>
			<name>checkbox_1452071521461</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>0</is_system>
			<value>undefined</value>
		</checkbox_1452071521461>
	</lib_data>',78897,102587,-102587