

use mapform

--select * from library_systemdata where contactid=102587

exec usp_GetLibraryData '<lib_json>
		<AP1Fname>
			<name>AP1Fname</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP1Fname>
		<AP1MName>
			<name>AP1MName</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP1MName>
		<AP1Lname>
			<name>AP1Lname</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP1Lname>
		<AP1ActAge>
			<name>AP1ActAge</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP1ActAge>
		<AP1Age>
			<name>AP1Age</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP1Age>
		<AP1BirthCity>
			<name>AP1BirthCity</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP1BirthCity>
		<AP1BirthCountry>
			<name>AP1BirthCountry</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP1BirthCountry>
		<AP1BirthName>
			<name>AP1BirthName</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP1BirthName>
		<AP1BirthState>
			<name>AP1BirthState</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP1BirthState>
		<AP1CellPhone>
			<name>AP1CellPhone</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP1CellPhone>
		<AP1Degree>
			<name>AP1Degree</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP1Degree>
		<AP1DegreeYear>
			<name>AP1DegreeYear</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP1DegreeYear>
		<AP1DOB>
			<name>AP1DOB</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP1DOB>
		<AP1Email>
			<name>AP1Email</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP1Email>
		<AP1Ethnicity>
			<name>AP1Ethnicity</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP1Ethnicity>
		<AP1Gender>
			<name>AP1Gender</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP1Gender>
		<AP1Nickname>
			<name>AP1Nickname</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP1Nickname>
		<AP1Race>
			<name>AP1Race</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP1Race>
		<AP1SSN>
			<name>AP1SSN</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP1SSN>
		<AP1County>
			<name>AP1County</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP1County>
		<AP1WorkPhone>
			<name>AP1WorkPhone</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP1WorkPhone>
		<AP2Fname>
			<name>AP2Fname</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP2Fname>
		<AP2Lname>
			<name>AP2Lname</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP2Lname>
		<AP2MName>
			<name>AP2MName</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP2MName>
		<AP2ActAge>
			<name>AP2ActAge</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP2ActAge>
		<AP2Age>
			<name>AP2Age</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP2Age>
		<AP2Add1>
			<name>AP2Add1</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP2Add1>
		<AP2Add2>
			<name>AP2Add2</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP2Add2>
		<AP2BirthCity>
			<name>AP2BirthCity</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP2BirthCity>
		<AP2BirthCountry>
			<name>AP2BirthCountry</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP2BirthCountry>
		<AP2BirthName>
			<name>AP2BirthName</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP2BirthName>
		<AP2BirthState>
			<name>AP2BirthState</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP2BirthState>
		<AP2CellPhone>
			<name>AP2CellPhone</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP2CellPhone>
		<AP2City>
			<name>AP2City</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP2City>
		<AP2County>
			<name>AP2County</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP2County>
		<AP2Country>
			<name>AP2Country</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP2Country>
		<AP2Degree>
			<name>AP2Degree</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP2Degree>
		<AP2DOB>
			<name>AP2DOB</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP2DOB>
		<AP2Email>
			<name>AP2Email</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP2Email>
		<AP2Ethnicity>
			<name>AP2Ethnicity</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP2Ethnicity>
		<AP2Gender>
			<name>AP2Gender</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP2Gender>
		<AP2Nickname>
			<name>AP2Nickname</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP2Nickname>
		<AP2WorkPhone>
			<name>AP2WorkPhone</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP2WorkPhone>
		<HomePhone>
			<name>HomePhone</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</HomePhone>
		<City>
			<name>City</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</City>
		<State>
			<name>State</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</State>
		<Zip>
			<name>Zip</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</Zip>
		<Add2>
			<name>Add2</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</Add2>
		<Add1>
			<name>Add1</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</Add1>
		<ap1signature>
			<name>ap1signature</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</ap1signature>
		<ap2signature>
			<name>ap2signature</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</ap2signature>
		<Med_1Sex>
			<name>Med_1Sex</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>0</is_system>
		</Med_1Sex>
		<Med_2Sex>
			<name>Med_2Sex</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>0</is_system>
		</Med_2Sex>
		<AP2SSN>
			<name>AP2SSN</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</AP2SSN>
		<Country>
			<name>Country</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</Country>
		<County>
			<name>County</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>true</is_system>
		</County>
		<radio_1452071124454>
			<name>radio_1452071124454</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>0</is_system>
		</radio_1452071124454>
		<radio_1452071125682>
			<name>radio_1452071125682</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>0</is_system>
		</radio_1452071125682>
		<radio_1452071126181>
			<name>radio_1452071126181</name>
			<scope>0</scope>
			<program_id>0</program_id>
			<connection_id>353509</connection_id>
			<is_system>0</is_system>
		</radio_1452071126181>
	</lib_json>',78897,102587,-102587



