USE MAPFACQB_STAGE
go

/******************Add column OLDUSER_ID ************************************************/
IF NOT EXISTS(SELECT * FROM sys.columns WHERE Name = N'OLDUSER_ID' AND Object_ID = Object_ID(N'FORMMAKER_77_preliminaryapplication'))    
BEGIN
	ALTER TABLE FORMMAKER_77_preliminaryapplication
	ADD OLDUSER_ID VARCHAR (5)
END
GO
IF NOT EXISTS(SELECT * FROM sys.columns WHERE Name = N'OLDUSER_ID' AND Object_ID = Object_ID(N'FORMMAKER_77_applicationchecklistforinternationaladoptions'))    
BEGIN
	ALTER TABLE FORMMAKER_77_applicationchecklistforinternationaladoptions
	ADD OLDUSER_ID VARCHAR (5)
END
GO
IF NOT EXISTS(SELECT * FROM sys.columns WHERE Name = N'OLDUSER_ID' AND Object_ID = Object_ID(N'FORMMAKER_77_topicsfordiscussion'))    
BEGIN
	ALTER TABLE FORMMAKER_77_topicsfordiscussion
	ADD OLDUSER_ID VARCHAR (5)
END
GO
IF NOT EXISTS(SELECT * FROM sys.columns WHERE Name = N'OLDUSER_ID' AND Object_ID = Object_ID(N'FORMMAKER_77_instructionsforreleaseofinformationforms'))    
BEGIN
	ALTER TABLE FORMMAKER_77_instructionsforreleaseofinformationforms
	ADD OLDUSER_ID VARCHAR (5)
END
GO
IF NOT EXISTS(SELECT * FROM sys.columns WHERE Name = N'OLDUSER_ID' AND Object_ID = Object_ID(N'FORMMAKER_77_topicsfordiscussion_1'))    
BEGIN
	ALTER TABLE FORMMAKER_77_topicsfordiscussion_1
	ADD OLDUSER_ID VARCHAR (5)
END
GO
IF NOT EXISTS(SELECT * FROM sys.columns WHERE Name = N'OLDUSER_ID' AND Object_ID = Object_ID(N'FORMMAKER_77_formalapplication_1'))    
BEGIN
	ALTER TABLE FORMMAKER_77_formalapplication_1
	ADD OLDUSER_ID VARCHAR (5)
END
GO
IF NOT EXISTS(SELECT * FROM sys.columns WHERE Name = N'OLDUSER_ID' AND Object_ID = Object_ID(N'FORMMAKER_77_adoptiveapplicantfinancialstatement'))    
BEGIN
	ALTER TABLE FORMMAKER_77_adoptiveapplicantfinancialstatement
	ADD OLDUSER_ID VARCHAR (5)
END
GO
IF NOT EXISTS(SELECT * FROM sys.columns WHERE Name = N'OLDUSER_ID' AND Object_ID = Object_ID(N'FORMMAKER_77_currentstateofresidency'))    
BEGIN
	ALTER TABLE FORMMAKER_77_currentstateofresidency
	ADD OLDUSER_ID VARCHAR (5)
END
GO
/**********************************************************************************************/
/*********************Insert into FORMMAKER_77_preliminaryapplication***********************/
INSERT INTO FORMMAKER_77_preliminaryapplication
(
user_id
,key_id
,input_ap1fname
,input_ap2fname
,input_ap1mname
,input_ap2mname
,input_ap1lname
,input_ap2lname
,input_add1
,input_add2
,input_cityorviloortownap1_41
,input_cityorviloortownap2_42
,input_state
,input_ap2state
,input_zip
,input_zipap2_44
,input_ap1cellphone
,input_ap2cellphone
,input_ap1workphone
,input_ap2workphone
,input_ap1email
,input_ap2email
,input_ap1dob
,input_ap2dob
,input_citizenshipap1_81
,input_citizenshipap2_46
,input_ap1education_47
,input_ap2education_48
,input_ap1occ_49
,input_ap2occ_50
,input_emp1fname
,input_emp2fname
,input_ap1marraigedate2
,input_ap2marraigedate2
,input_ap1premar_53
,input_ap2premar_54
,input_noofpremarap1_55
,input_noofpremarap2_56
,input_rel1fname
,input_rel1lname
,input_rel1gender
,input_rel1dob
,input_rel1relationship
,input_child1living_57
,input_rel2fname
,input_rel2lname
,input_rel2gender
,input_rel2dob
,input_rel2relationship
,input_child2living_58
,input_rel3fname
,input_rel3lname
,input_rel3gender
,input_rel3dob
,input_rel3relationship
,input_child3living_59
,input_rel4fname
,input_rel4lname
,input_rel4gender
,input_rel4dob
,input_rel4relationship
,input_child4living_60
,input_ap1grossincome
,input_ap2grossincome
,input_ap1sourceofotherinc_61
,input_ap2sourceofotherinc_62
,input_ap1amtofotherinc
,input_ap2amtofotherinc
,input_totalanninc
,input_savings
,input_investments
,input_totalassets
,input_intadoptioncountry_63
,input_domestic_64
,input_racilalaccept_65
,input_biracial_66
,input_agerange
,input_gender
,input_siblings_67
,input_noofchild_68
,input_med_1height
,input_med_2height
,input_med_2weight
,input_med_1weight
,input_ap1bmi_69
,input_bmiap2_70
,input_communicablediseasesn
,input_ap1tumor
,input_ap2timor
,input_ap2communicabledisease
,input_ap1heartdisease_71
,input_heartdiseaseap2
,input_ap1depression_72
,input_ap2depression
,input_ap1counselling
,input_ap2counselling
,input_ap1alcoholism
,input_ap2alcoholism
,input_geneticdisease_73
,input_ap1epilepsy
,input_ap2epilepsy
,input_ap2geneticdisease
,input_ap1diabetes
,input_ap2diabetes
,input_ap1operations
,input_ap2operations
,input_ap1physicalimpairment
,input_ap2physicalimpairment
,input_currentlypregap1
,input_currentlyprg
,input_anymedicationcurrently
,input_yestomedicondition
,input_prevhomestudy
,input_date_74
,input_agency_75
,input_typeofadoption
,input_adoptafterhs
,input_denidplacemnt
,input_refusedref
,input_childremovd
,input_histofarrest
,input_familycmembchildabuse
,input_histofsubstanceabuse
,input_domviolence
,input_detailedexp
,input_placingagency
,input_additionalinfo
,input_ap1signature
,input_signdate1
,input_signdate2
,input_ap2signature
,input_county
,input_ap2county_184
,input_addlempdetails
,ConnId
,ConnectionId
,isXML
,formFullData
,OLDUSER_ID
)

SELECT user_id+100000
,key_id
,input_ap1fname
,input_ap2fname
,input_ap1mname
,input_ap2mname
,input_ap1lname
,input_ap2lname
,input_add1
,input_add2
,input_cityorviloortownap1_41
,input_cityorviloortownap2_42
,input_state
,input_ap2state
,input_zip
,input_zipap2_44
,input_ap1cellphone
,input_ap2cellphone
,input_ap1workphone
,input_ap2workphone
,input_ap1email
,input_ap2email
,input_ap1dob
,input_ap2dob
,input_citizenshipap1_81
,input_citizenshipap2_46
,input_ap1education_47
,input_ap2education_48
,input_ap1occ_49
,input_ap2occ_50
,input_emp1fname
,input_emp2fname
,input_ap1marraigedate2
,input_ap2marraigedate2
,input_ap1premar_53
,input_ap2premar_54
,input_noofpremarap1_55
,input_noofpremarap2_56
,input_rel1fname
,input_rel1lname
,input_rel1gender
,input_rel1dob
,input_rel1relationship
,input_child1living_57
,input_rel2fname
,input_rel2lname
,input_rel2gender
,input_rel2dob
,input_rel2relationship
,input_child2living_58
,input_rel3fname
,input_rel3lname
,input_rel3gender
,input_rel3dob
,input_rel3relationship
,input_child3living_59
,input_rel4fname
,input_rel4lname
,input_rel4gender
,input_rel4dob
,input_rel4relationship
,input_child4living_60
,input_ap1grossincome
,input_ap2grossincome
,input_ap1sourceofotherinc_61
,input_ap2sourceofotherinc_62
,input_ap1amtofotherinc
,input_ap2amtofotherinc
,input_totalanninc
,input_savings
,input_investments
,input_totalassets
,input_intadoptioncountry_63
,input_domestic_64
,input_racilalaccept_65
,input_biracial_66
,input_agerange
,input_gender
,input_siblings_67
,input_noofchild_68
,input_med_1height
,input_med_2height
,input_med_2weight
,input_med_1weight
,input_ap1bmi_69
,input_bmiap2_70
,input_communicablediseasesn
,input_ap1tumor
,input_ap2timor
,input_ap2communicabledisease
,input_ap1heartdisease_71
,input_heartdiseaseap2
,input_ap1depression_72
,input_ap2depression
,input_ap1counselling
,input_ap2counselling
,input_ap1alcoholism
,input_ap2alcoholism
,input_geneticdisease_73
,input_ap1epilepsy
,input_ap2epilepsy
,input_ap2geneticdisease
,input_ap1diabetes
,input_ap2diabetes
,input_ap1operations
,input_ap2operations
,input_ap1physicalimpairment
,input_ap2physicalimpairment
,input_currentlypregap1
,input_currentlyprg
,input_anymedicationcurrently
,input_yestomedicondition
,input_prevhomestudy
,input_date_74
,input_agency_75
,input_typeofadoption
,input_adoptafterhs
,input_denidplacemnt
,input_refusedref
,input_childremovd
,input_histofarrest
,input_familycmembchildabuse
,input_histofsubstanceabuse
,input_domviolence
,input_detailedexp
,input_placingagency
,input_additionalinfo
,input_ap1signature
,input_signdate1
,input_signdate2
,input_ap2signature
,input_county
,input_ap2county_184
,input_addlempdetails
,((ConnId*-1)+100000)*-1
,ConnectionId+100000
,isXML
,formFullData
,USER_ID
FROM MAPFAC.DBO.FORMMAKER_77_preliminaryapplication  WHERE USER_ID >=13433

--13

/*************************FORMMAKER_77_applicationchecklistforinternationaladoptions*************************/

INSERT INTO FORMMAKER_77_applicationchecklistforinternationaladoptions
(
user_id
,key_id
,input_checklist1
,input_selfstudy
,input_ccpp
,input_erl
,input_checklistfortopic
,input_photocopy
,input_licensedriver
,input_creditreport
,ConnId
,ConnectionId
,isXML
,formFullData
,OLDUSER_ID
)
SELECT user_id+100000
,key_id
,input_checklist1
,input_selfstudy
,input_ccpp
,input_erl
,input_checklistfortopic
,input_photocopy
,input_licensedriver
,input_creditreport
,((ConnId*-1)+100000)*-1
,ConnectionId+100000
,isXML
,formFullData
,USER_ID
FROM MAPFAC.DBO.FORMMAKER_77_applicationchecklistforinternationaladoptions  
WHERE USER_ID >=13433

--2

/*************************FORMMAKER_77_topicsfordiscussion*************************/

INSERT INTO FORMMAKER_77_topicsfordiscussion
(
user_id
,key_id
,input_ap1fname
,input_ap1lname
,input_check
,input_list
,ConnId
,ConnectionId
,isXML
,formFullData
,OLDUSER_ID
)
SELECT user_id+100000
,key_id
,input_ap1fname
,input_ap1lname
,input_check
,input_list
,((ConnId*-1)+100000)*-1
,ConnectionId+100000
,isXML
,formFullData
,USER_ID
FROM MAPFAC.DBO.FORMMAKER_77_topicsfordiscussion  WHERE USER_ID >=13433

--2

/*************************FORMMAKER_77_instructionsforreleaseofinformationforms*************************/

INSERT INTO FORMMAKER_77_instructionsforreleaseofinformationforms
(
user_id
,key_id
,input_ap1fname
,input_ap1mname
,input_ap1lname
,input_add1
,input_add2
,input_city
,input_state
,input_zip
,input_rfno
,input_ap1signature
,ConnId
,ConnectionId
,isXML
,formFullData
,OLDUSER_ID
)

SELECT user_id+100000
,key_id
,input_ap1fname
,input_ap1mname
,input_ap1lname
,input_add1
,input_add2
,input_city
,input_state
,input_zip
,input_rfno
,input_ap1signature
,((ConnId*-1)+100000)*-1
,ConnectionId+100000
,isXML
,formFullData
,USER_ID
FROM MAPFAC.DBO.FORMMAKER_77_instructionsforreleaseofinformationforms  
WHERE USER_ID >=13433

--2

/*************************FORMMAKER_77_topicsfordiscussion_1*************************/

INSERT INTO FORMMAKER_77_topicsfordiscussion_1
(
user_id
,key_id
,input_ap2fname
,input_ap2lname
,input_check
,input_list
,ConnId
,ConnectionId
,isXML
,formFullData
,OLDUSER_ID
)

SELECT user_id+100000
,key_id
,input_ap2fname
,input_ap2lname
,input_check
,input_list
,((ConnId*-1)+100000)*-1
,ConnectionId+100000
,isXML
,formFullData
,USER_ID
FROM MAPFAC.DBO.FORMMAKER_77_topicsfordiscussion_1
WHERE USER_ID >=13433

--2

/*************************FORMMAKER_77_formalapplication_1*************************/
INSERT INTO FORMMAKER_77_formalapplication_1
(
user_id
,key_id
,input_ap1fname
,input_ap2fname
,input_ap1mname
,input_ap2mname
,input_ap1lname
,input_ap2lname
,input_ap1aliasename_76
,input_ap2aliasename_77
,input_add1
,input_add2
,input_city
,input_ap2city_78
,input_county
,input_ap2county
,input_state
,input_ap2state_79
,input_zip
,input_zipap2_44
,input_homephone
,input_ap2homephone_80
,input_ap1cellphone
,input_ap2cellphone
,input_ap1workphone
,input_ap2workphone
,input_ap1email
,input_ap2email
,input_ap1dob
,input_ap2dob
,input_ap1birthcity
,input_ap2birthcity
,input_ap1ethnicity
,input_ap2ethnicity
,input_ap1race
,input_ap2race
,input_citizenshipap2_46
,input_citizenshipap1_81
,input_ap1alienno
,input_ap2alienno_82
,input_ap1ssn
,input_ap2ssn
,input_ap1religion
,input_ap2religion
,input_ap1marraigedate2
,input_ap2marraigedate2
,input_ap1marplace_83
,input_ap2marplace_84
,input_ap1premarsponame_85
,input_ap1marraigedate
,input_premarplaceap1
,input_ap1terminwhere_86
,input_ap1terminhow_87
,input_ap2prespousename_88
,input_ap2terminationdate
,input_placepremarterap2_89
,input_ap2reasonter_90
,input_termwhereap2_91
,input_ap1fathername_92
,input_ap2fathername_93
,input_fatheroccap1_94
,input_ap2fatherocc_95
,input_ap1fatherliving_96
,input_ap2fatherliving_97
,input_ap1mothername_98
,input_ap2mothersname_99
,input_ap1motherocc_100
,input_ap2mothersocc_101
,input_ap1motherliving_102
,input_ap2motherliving_103
,input_ap1sib1name_104
,input_ap2sib1name_105
,input_ap1sib1dob_106
,input_ap2sib1dob_107
,input_ap1sib2name_108
,input_ap2sib2name_109
,input_ap1sib2dob_110
,input_ap2sib2dob_111
,input_ap1sib3name_112
,input_ap2sib3name_113
,input_ap2dobsib3
,input_ap2sib3dob_115
,input_rel1fname
,input_rel1lname
,input_child1placeofbirth_116
,input_rel1gender
,input_rel1dob
,input_child1ssn_117
,input_rel1relationship
,input_child1living_57
,input_rel2fname
,input_rel2lname
,input_child2birthplace_118
,input_rel2gender
,input_rel2dob
,input_child2ssn_119
,input_rel2relationship
,input_child2living_58
,input_rel3fname
,input_rel3lname
,input_child3birthplace_120
,input_rel3gender
,input_child3ssn_121
,input_rel3dob
,input_rel3relationship
,input_child3living_59
,input_rel4fname
,input_rel4lname
,input_child4placeofbirth_122
,input_rel4gender
,input_rel4dob
,input_child4ssn_123
,input_rel4relationship
,input_rel5fname
,input_rel5lname
,input_rel5gender
,input_rel5dob
,input_otheradult1ssn_124
,input_adult1relap1_125
,input_adult1relap2_126
,input_rel6fname
,input_rel6lname
,input_rel6gender
,input_rel6dob
,input_adult2ssn_127
,input_adult2relap1_128
,input_adult2relap2_129
,input_reason
,input_qualities
,input_childlessreason
,input_seriouscon
,input_treatmentdetails
,input_releaseofcontact
,input_hometype
,input_noofrooms_130
,input_noofbedrooms_131
,input_mortgage
,input_rent
,input_squarefootage
,input_lotsize
,input_ap1collegename
,input_ap2collegename
,input_ap1collegecity
,input_ap2collegecity
,input_ap1collegestate
,input_ap2collegestate
,input_c1datesap1
,input_c1datesap2
,input_degreeap1
,input_degreeap2
,input_college2ap1
,input_college2ap2
,input_cityap1college2
,input_cityap2college2
,input_ap1state2
,input_ap2state2
,input_ap1datescoll2
,input_ap1datescol22
,input_ap1degree2
,input_ap2degree2
,input_vocationap1
,input_vocationap2
,input_ap1dates1
,input_ap2dates1
,input_ap1degreevoc
,input_ap2degreevoc
,input_ap1hsname1
,input_ap2hsname1
,input_ap1cityhs1
,input_ap2cityhs1
,input_ap1state2hs
,input_ap2state2hs
,input_ap1sateshs1
,input_ap2dateshs1
,input_ap1degreehs1
,input_ap2degreehs1
,input_ap1hsname2
,input_ap2hsname2
,input_ap1cityhs2
,input_ap2cityhs2
,input_ap1statehs2
,input_ap2statehs2
,input_ap1dasteshs2
,input_ap2dasteshs2
,input_ap1degreehs2
,input_ap2degreehs2
,input_emp1fname
,input_emp2fname
,input_ap1occ_49
,input_ap2occ_50
,input_ap1years
,input_yearsap2
,input_emp1salary
,input_emp2salary
,input_type
,input_typeap2
,input_brachap1
,input_branchap2
,input_ap1preocc_132
,input_ap2preocc
,input_yearspreap1
,input_yearspreap2
,input_ap1preemplo
,input_ap2preemplo
,input_ap1preocc2
,input_ocupat
,input_ap1years2
,input_ap2years2
,input_annualap1
,input_ap2annual
,input_typeap12
,input_trypeap1
,input_grandparentnameap1
,input_grandparentnameap2
,input_ap1gpadd
,input_gpaddap2
,input_ap1citygp
,input_ap2citygp
,input_ap1stategp
,input_ap2stategp
,input_zipap1gp
,input_zipstateap2
,input_ref1fname
,input_ref1lname
,input_ref1add1
,input_ref1add2
,input_neighborphone
,input_ref1city
,input_ref1state
,input_ref1zip
,input_ref2fname
,input_ref2lname
,input_ref2add1
,input_ref2add2
,input_ref2phone
,input_ref2city
,input_ref2state
,input_ref2zip
,input_ref3fname
,input_ref3lname
,input_ref3add1
,input_ref3add2
,input_ref3phone
,input_ref3city
,input_ref3state
,input_ref3zip
,input_ref4fname
,input_ref4lname
,input_ref4add1
,input_ref4add2
,input_ref4phone
,input_ref4city
,input_ref4state
,input_ref4zip
,input_ap1employer
,input_emp1add1
,input_employerphone
,input_emp1city
,input_emp1state
,input_emp1zip
,input_ap1empname
,input_emp2add1
,input_ap2emphone
,input_emp2city
,input_emp2state
,input_emp2zip
,input_ref5fname
,input_ref5lname
,input_ref5add1
,input_ref5phone
,input_ref5city
,input_ref5state
,input_ref5zip
,input_ref6fname
,input_ref6lname
,input_ref6add1
,input_ref6phone
,input_ref6city
,input_ref6state
,input_ref6zip
,input_ap1street1_146
,input_ap2street1_147
,input_ap1city1
,input_ap2city2_148
,input_ap1county1_149
,input_ap2county1_150
,input_ap1state1_151
,input_ap2state1
,input_ap1zip1
,input_ap2zip1
,input_ap1datesoffres1
,input_ap2datesofres1
,input_ap1forcountry1_152
,input_ap2forcountry1
,input_ap1street2
,input_ap2street2
,input_ap1city2
,input_ap2city
,input_ap1county2
,input_ap2county2
,input_ap1state
,input_ap2state
,input_ap1zip2
,input_ap2zip2
,input_ap1street3
,input_ap2street3
,input_ap1county3
,input_ap2county3
,input_ap1state3
,input_ap2state3
,input_ap1city3
,input_ap2city3
,input_ap1zip3
,input_ap2zip3
,input_ap1datesofres2
,input_ap2datesofres2
,input_ap2forcountry2
,input_ap2forcountry
,input_ap1street4
,input_ap2street4
,input_ap1city4
,input_ap2city4
,input_ap1county4
,input_ap2county4
,input_ap1state4
,input_ap2state4
,input_ap1zip4
,input_ap2zip4
,input_ap1datesofres3
,input_ap2datesofres4
,input_ap1forcountry3
,input_ap2forcountry3
,input_ap1datesofres4
,input_ap2datesofres
,input_ap1forcountry4
,input_ap2forcountry4
,input_ap1street5
,input_ap2street5
,input_ap1city5
,input_ap2city5
,input_ap1county5
,input_ap2county5
,input_ap2state5
,input_ap2states
,input_ap1zip5
,input_ap2zip5
,input_ap1datesofres5
,input_ap2datesofres5
,input_ap1forcountry5
,input_ap2forcountry5
,input_histofarrest
,input_ifyes1
,input_childabuseinvesti
,input_ifyes2
,input_subabusehist
,input_ifyes3
,input_domviolencehist
,input_hscompleted
,input_ifyes4
,input_ap1signature
,input_signdate1
,input_ap2signature
,input_signdate2
,ConnId
,ConnectionId
,isXML
,formFullData
,OLDUser_ID
)

SELECT user_id+100000
,key_id
,input_ap1fname
,input_ap2fname
,input_ap1mname
,input_ap2mname
,input_ap1lname
,input_ap2lname
,input_ap1aliasename_76
,input_ap2aliasename_77
,input_add1
,input_add2
,input_city
,input_ap2city_78
,input_county
,input_ap2county
,input_state
,input_ap2state_79
,input_zip
,input_zipap2_44
,input_homephone
,input_ap2homephone_80
,input_ap1cellphone
,input_ap2cellphone
,input_ap1workphone
,input_ap2workphone
,input_ap1email
,input_ap2email
,input_ap1dob
,input_ap2dob
,input_ap1birthcity
,input_ap2birthcity
,input_ap1ethnicity
,input_ap2ethnicity
,input_ap1race
,input_ap2race
,input_citizenshipap2_46
,input_citizenshipap1_81
,input_ap1alienno
,input_ap2alienno_82
,input_ap1ssn
,input_ap2ssn
,input_ap1religion
,input_ap2religion
,input_ap1marraigedate2
,input_ap2marraigedate2
,input_ap1marplace_83
,input_ap2marplace_84
,input_ap1premarsponame_85
,input_ap1marraigedate
,input_premarplaceap1
,input_ap1terminwhere_86
,input_ap1terminhow_87
,input_ap2prespousename_88
,input_ap2terminationdate
,input_placepremarterap2_89
,input_ap2reasonter_90
,input_termwhereap2_91
,input_ap1fathername_92
,input_ap2fathername_93
,input_fatheroccap1_94
,input_ap2fatherocc_95
,input_ap1fatherliving_96
,input_ap2fatherliving_97
,input_ap1mothername_98
,input_ap2mothersname_99
,input_ap1motherocc_100
,input_ap2mothersocc_101
,input_ap1motherliving_102
,input_ap2motherliving_103
,input_ap1sib1name_104
,input_ap2sib1name_105
,input_ap1sib1dob_106
,input_ap2sib1dob_107
,input_ap1sib2name_108
,input_ap2sib2name_109
,input_ap1sib2dob_110
,input_ap2sib2dob_111
,input_ap1sib3name_112
,input_ap2sib3name_113
,input_ap2dobsib3
,input_ap2sib3dob_115
,input_rel1fname
,input_rel1lname
,input_child1placeofbirth_116
,input_rel1gender
,input_rel1dob
,input_child1ssn_117
,input_rel1relationship
,input_child1living_57
,input_rel2fname
,input_rel2lname
,input_child2birthplace_118
,input_rel2gender
,input_rel2dob
,input_child2ssn_119
,input_rel2relationship
,input_child2living_58
,input_rel3fname
,input_rel3lname
,input_child3birthplace_120
,input_rel3gender
,input_child3ssn_121
,input_rel3dob
,input_rel3relationship
,input_child3living_59
,input_rel4fname
,input_rel4lname
,input_child4placeofbirth_122
,input_rel4gender
,input_rel4dob
,input_child4ssn_123
,input_rel4relationship
,input_rel5fname
,input_rel5lname
,input_rel5gender
,input_rel5dob
,input_otheradult1ssn_124
,input_adult1relap1_125
,input_adult1relap2_126
,input_rel6fname
,input_rel6lname
,input_rel6gender
,input_rel6dob
,input_adult2ssn_127
,input_adult2relap1_128
,input_adult2relap2_129
,input_reason
,input_qualities
,input_childlessreason
,input_seriouscon
,input_treatmentdetails
,input_releaseofcontact
,input_hometype
,input_noofrooms_130
,input_noofbedrooms_131
,input_mortgage
,input_rent
,input_squarefootage
,input_lotsize
,input_ap1collegename
,input_ap2collegename
,input_ap1collegecity
,input_ap2collegecity
,input_ap1collegestate
,input_ap2collegestate
,input_c1datesap1
,input_c1datesap2
,input_degreeap1
,input_degreeap2
,input_college2ap1
,input_college2ap2
,input_cityap1college2
,input_cityap2college2
,input_ap1state2
,input_ap2state2
,input_ap1datescoll2
,input_ap1datescol22
,input_ap1degree2
,input_ap2degree2
,input_vocationap1
,input_vocationap2
,input_ap1dates1
,input_ap2dates1
,input_ap1degreevoc
,input_ap2degreevoc
,input_ap1hsname1
,input_ap2hsname1
,input_ap1cityhs1
,input_ap2cityhs1
,input_ap1state2hs
,input_ap2state2hs
,input_ap1sateshs1
,input_ap2dateshs1
,input_ap1degreehs1
,input_ap2degreehs1
,input_ap1hsname2
,input_ap2hsname2
,input_ap1cityhs2
,input_ap2cityhs2
,input_ap1statehs2
,input_ap2statehs2
,input_ap1dasteshs2
,input_ap2dasteshs2
,input_ap1degreehs2
,input_ap2degreehs2
,input_emp1fname
,input_emp2fname
,input_ap1occ_49
,input_ap2occ_50
,input_ap1years
,input_yearsap2
,input_emp1salary
,input_emp2salary
,input_type
,input_typeap2
,input_brachap1
,input_branchap2
,input_ap1preocc_132
,input_ap2preocc
,input_yearspreap1
,input_yearspreap2
,input_ap1preemplo
,input_ap2preemplo
,input_ap1preocc2
,input_ocupat
,input_ap1years2
,input_ap2years2
,input_annualap1
,input_ap2annual
,input_typeap12
,input_trypeap1
,input_grandparentnameap1
,input_grandparentnameap2
,input_ap1gpadd
,input_gpaddap2
,input_ap1citygp
,input_ap2citygp
,input_ap1stategp
,input_ap2stategp
,input_zipap1gp
,input_zipstateap2
,input_ref1fname
,input_ref1lname
,input_ref1add1
,input_ref1add2
,input_neighborphone
,input_ref1city
,input_ref1state
,input_ref1zip
,input_ref2fname
,input_ref2lname
,input_ref2add1
,input_ref2add2
,input_ref2phone
,input_ref2city
,input_ref2state
,input_ref2zip
,input_ref3fname
,input_ref3lname
,input_ref3add1
,input_ref3add2
,input_ref3phone
,input_ref3city
,input_ref3state
,input_ref3zip
,input_ref4fname
,input_ref4lname
,input_ref4add1
,input_ref4add2
,input_ref4phone
,input_ref4city
,input_ref4state
,input_ref4zip
,input_ap1employer
,input_emp1add1
,input_employerphone
,input_emp1city
,input_emp1state
,input_emp1zip
,input_ap1empname
,input_emp2add1
,input_ap2emphone
,input_emp2city
,input_emp2state
,input_emp2zip
,input_ref5fname
,input_ref5lname
,input_ref5add1
,input_ref5phone
,input_ref5city
,input_ref5state
,input_ref5zip
,input_ref6fname
,input_ref6lname
,input_ref6add1
,input_ref6phone
,input_ref6city
,input_ref6state
,input_ref6zip
,input_ap1street1_146
,input_ap2street1_147
,input_ap1city1
,input_ap2city2_148
,input_ap1county1_149
,input_ap2county1_150
,input_ap1state1_151
,input_ap2state1
,input_ap1zip1
,input_ap2zip1
,input_ap1datesoffres1
,input_ap2datesofres1
,input_ap1forcountry1_152
,input_ap2forcountry1
,input_ap1street2
,input_ap2street2
,input_ap1city2
,input_ap2city
,input_ap1county2
,input_ap2county2
,input_ap1state
,input_ap2state
,input_ap1zip2
,input_ap2zip2
,input_ap1street3
,input_ap2street3
,input_ap1county3
,input_ap2county3
,input_ap1state3
,input_ap2state3
,input_ap1city3
,input_ap2city3
,input_ap1zip3
,input_ap2zip3
,input_ap1datesofres2
,input_ap2datesofres2
,input_ap2forcountry2
,input_ap2forcountry
,input_ap1street4
,input_ap2street4
,input_ap1city4
,input_ap2city4
,input_ap1county4
,input_ap2county4
,input_ap1state4
,input_ap2state4
,input_ap1zip4
,input_ap2zip4
,input_ap1datesofres3
,input_ap2datesofres4
,input_ap1forcountry3
,input_ap2forcountry3
,input_ap1datesofres4
,input_ap2datesofres
,input_ap1forcountry4
,input_ap2forcountry4
,input_ap1street5
,input_ap2street5
,input_ap1city5
,input_ap2city5
,input_ap1county5
,input_ap2county5
,input_ap2state5
,input_ap2states
,input_ap1zip5
,input_ap2zip5
,input_ap1datesofres5
,input_ap2datesofres5
,input_ap1forcountry5
,input_ap2forcountry5
,input_histofarrest
,input_ifyes1
,input_childabuseinvesti
,input_ifyes2
,input_subabusehist
,input_ifyes3
,input_domviolencehist
,input_hscompleted
,input_ifyes4
,input_ap1signature
,input_signdate1
,input_ap2signature
,input_signdate2
,((ConnId*-1)+100000)*-1
,ConnectionId+100000
,isXML
,formFullData
,USER_ID
FROM MAPFAC.DBO.FORMMAKER_77_formalapplication_1
WHERE USER_ID >=13433

--4

/*************************FORMMAKER_77_adoptiveapplicantfinancialstatement*************************/
INSERT INTO FORMMAKER_77_adoptiveapplicantfinancialstatement
(
user_id
,key_id
,input_ap1fname
,input_ap1lname
,input_ap2fname
,input_ap2lname
,input_depadults
,input_depchildren
,input_famember1
,input_memb1grosspay
,input_memb2netpay
,input_famember2
,input_memb2grosspay
,input_memb1netpay
,input_otherinc
,input_totalincome
,input_rent
,input_boats
,input_homeequity
,input_tuition
,input_propertytaxes
,input_food
,input_inshome
,input_clothing
,input_telephone
,input_cellphone
,input_heat
,input_electric
,input_cableservice
,input_watersewer
,input_trash
,input_mediexp
,input_medins
,input_disabilityions
,input_entertainment
,input_gifts
,input_lifeins
,input_carins
,input_homemaintenance
,input_autolicense
,input_personalcare
,input_charity
,input_childcare
,input_religiouscontri
,input_schoolsupplies
,input_gasoline
,input_creditcardpayments
,input_vacations
,input_schooloan
,input_lunch
,input_unreimbursedexp
,input_cloth
,input_empgifts
,input_childsupportali
,input_regsavings
,input_investmentsretire
,input_car1loan
,input_car2loan
,input_selfemptaxes
,input_otherselfempexp
,input_otherloanpay
,input_subtotal1
,input_subtotal2
,input_totalexp
,input_resimktvalue
,input_otherrealestatemktval
,input_car1value
,input_car1
,input_car2value
,input_car2
,input_boatrv
,input_boatvalue_153
,input_savings
,input_retirement
,input_stocksandbonds
,input_investmentsassets
,input_otherassetsvalue
,input_otherassets
,input_totalassets
,input_residencemortagage
,input_othermortagage
,input_car1liabilty
,input_car1name
,input_carloan
,input_car2loans
,input_boatsli
,input_otherloans
,input_otherloansliab
,input_creditcardss
,input_1
,input_2
,input_3
,input_otherloansvalue
,input_otherspecify1
,input_otherloansvalue2
,input_other
,input_totalaibilities
,input_excludedinc
,input_exincome1
,input_excludedinc2
,input_exincome2
,input_totalexincome
,input_liap1
,input_ap1limonthlycost
,input_liap1company
,input_liap2
,input_ap2li
,input_licompap1
,input_child1lifeins
,input_monthlycostchild1
,input_lifeinscompchild1
,input_child2li
,input_child2limonthlycost
,input_comchild2
,input_ch3lifeins
,input_child3monthlycost
,input_lifeinscompch3
,input_ap1medins
,input_ap1medinscost
,input_com
,input_medinsap2
,input_ap2moncost
,input_comp
,input_lifeinschil1
,input_childmedinscost
,input_compa
,input_child
,input_ap2monthcost
,input_co
,input_ap1medicaid1
,input_monap
,input_apcom
,input_apmedica
,input_monap2
,input_ap2com
,input_child1medicaid
,input_c
,input_child1mon
,input_chmed2
,input_ch2mon
,input_ch2com
,input_ch1
,input_ch3mon
,input_compch3
,input_dis
,input_dismonth
,input_comch3
,input_otherins
,input_totalcov
,input_company1
,input_info_155
,input_ap1signature
,input_dateap1
,input_date2
,input_ap2signature
,ConnId
,ConnectionId
,isXML
,formFullData
,OLDUSER_ID
)
SELECT user_id+100000
,key_id
,input_ap1fname
,input_ap1lname
,input_ap2fname
,input_ap2lname
,input_depadults
,input_depchildren
,input_famember1
,input_memb1grosspay
,input_memb2netpay
,input_famember2
,input_memb2grosspay
,input_memb1netpay
,input_otherinc
,input_totalincome
,input_rent
,input_boats
,input_homeequity
,input_tuition
,input_propertytaxes
,input_food
,input_inshome
,input_clothing
,input_telephone
,input_cellphone
,input_heat
,input_electric
,input_cableservice
,input_watersewer
,input_trash
,input_mediexp
,input_medins
,input_disabilityions
,input_entertainment
,input_gifts
,input_lifeins
,input_carins
,input_homemaintenance
,input_autolicense
,input_personalcare
,input_charity
,input_childcare
,input_religiouscontri
,input_schoolsupplies
,input_gasoline
,input_creditcardpayments
,input_vacations
,input_schooloan
,input_lunch
,input_unreimbursedexp
,input_cloth
,input_empgifts
,input_childsupportali
,input_regsavings
,input_investmentsretire
,input_car1loan
,input_car2loan
,input_selfemptaxes
,input_otherselfempexp
,input_otherloanpay
,input_subtotal1
,input_subtotal2
,input_totalexp
,input_resimktvalue
,input_otherrealestatemktval
,input_car1value
,input_car1
,input_car2value
,input_car2
,input_boatrv
,input_boatvalue_153
,input_savings
,input_retirement
,input_stocksandbonds
,input_investmentsassets
,input_otherassetsvalue
,input_otherassets
,input_totalassets
,input_residencemortagage
,input_othermortagage
,input_car1liabilty
,input_car1name
,input_carloan
,input_car2loans
,input_boatsli
,input_otherloans
,input_otherloansliab
,input_creditcardss
,input_1
,input_2
,input_3
,input_otherloansvalue
,input_otherspecify1
,input_otherloansvalue2
,input_other
,input_totalaibilities
,input_excludedinc
,input_exincome1
,input_excludedinc2
,input_exincome2
,input_totalexincome
,input_liap1
,input_ap1limonthlycost
,input_liap1company
,input_liap2
,input_ap2li
,input_licompap1
,input_child1lifeins
,input_monthlycostchild1
,input_lifeinscompchild1
,input_child2li
,input_child2limonthlycost
,input_comchild2
,input_ch3lifeins
,input_child3monthlycost
,input_lifeinscompch3
,input_ap1medins
,input_ap1medinscost
,input_com
,input_medinsap2
,input_ap2moncost
,input_comp
,input_lifeinschil1
,input_childmedinscost
,input_compa
,input_child
,input_ap2monthcost
,input_co
,input_ap1medicaid1
,input_monap
,input_apcom
,input_apmedica
,input_monap2
,input_ap2com
,input_child1medicaid
,input_c
,input_child1mon
,input_chmed2
,input_ch2mon
,input_ch2com
,input_ch1
,input_ch3mon
,input_compch3
,input_dis
,input_dismonth
,input_comch3
,input_otherins
,input_totalcov
,input_company1
,input_info_155
,input_ap1signature
,input_dateap1
,input_date2
,input_ap2signature
,((ConnId*-1)+100000)*-1
,ConnectionId+100000
,isXML
,formFullData
,USER_ID
FROM MAPFAC.DBO.FORMMAKER_77_adoptiveapplicantfinancialstatement
WHERE USER_ID >=13433

--2

/*************************FORMMAKER_77_currentstateofresidency*************************/

INSERT INTO FORMMAKER_77_currentstateofresidency
(
user_id
,key_id
,input_stateofresidence_156
,input_statename_157
,ConnId
,ConnectionId
,isXML
,formFullData
,OLDUSER_ID
)
SELECT user_id+100000
,key_id
,input_stateofresidence_156
,input_statename_157
,((ConnId*-1)+100000)*-1
,ConnectionId+100000
,isXML
,formFullData
,USER_ID
FROM MAPFAC.DBO.FORMMAKER_77_currentstateofresidency
WHERE USER_ID >=13433

--18